version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: marvel-saga-db
    restart: always
    environment:
      POSTGRES_DB: marvel_saga_db
      POSTGRES_USER: herick
      POSTGRES_PASSWORD: thunder5
    ports:
      - "5433:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  backend:
    build:
      context: ./marvel-backend
      dockerfile: Dockerfile
    container_name: marvel-saga-backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: marvel_saga_db
      DB_USER: herick
      DB_PASSWORD: thunder5

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marvel-saga-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://backend:4000/api"
    depends_on:
      - backend
